### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by faker320** [VariantConst/Marchkov-Helper#2]
1. 可以在设置里增加一个开关，允许用户自由决定要不要打开app自动预约班车，如果关闭自动预约功能，可以在首页展示已预约的下一班班车的二维码。
2. 预约界面根据时间自动调整燕园/昌平方向班车的展示顺序，如用户选择上午去燕园、下午去昌平，则在上午在预约界面优先展示去燕园的车次，下午相反。

**Comment by VariantConst** [comment]
好的，下一个版本会加入。但以下特性

> 如果关闭自动预约功能，可以在首页展示已预约的下一班班车的二维码。

我不计划加入。个人认为提前一小时以上展示乘车码没有意义，这会给用户造成困扰。

**Comment by VariantConst** [comment]
相关更改已在 iOS 版 v1.3.2 加入。

**Comment by VariantConst** [comment]
相关更改已在 iOS 版 v1.3.2 加入。
